"use client";
import Link from "next/link";
import { useState } from "react";
import { Search, Newspaper, Pencil } from "lucide-react";
type Item = { id: string; title: string; status: string; updated: string };
export function AdminNewsList({ items }: { items: Item[] }) {
  const [query, setQuery] = useState("");
  const [status, setStatus] = useState("all");
  const visible = items.filter(item => item.title.toLocaleLowerCase("nl").includes(query.toLocaleLowerCase("nl")) && (status === "all" || item.status === status));
  return <div className="admin-list-panel"><div className="admin-list-tools"><label className="admin-search"><Search size={17} /><input aria-label="Zoek op titel" placeholder="Zoek op titel…" value={query} onChange={e => setQuery(e.target.value)} /></label><select className="input admin-status-filter" aria-label="Filter op status" value={status} onChange={e => setStatus(e.target.value)}><option value="all">Alle statussen</option><option value="published">Gepubliceerd</option><option value="draft">Concept</option></select></div><div className="admin-table-scroll"><table className="admin-news-table"><thead><tr><th scope="col">Bericht</th><th scope="col">Status</th><th scope="col">Gewijzigd</th><th scope="col"><span className="sr-only">Actie</span></th></tr></thead><tbody>{visible.map(item => <tr key={item.id}><td><Link href={`/beheer/nieuws/${item.id}`}>{item.title}</Link></td><td><span className={`status ${item.status}`}>{item.status === "published" ? "Gepubliceerd" : "Concept"}</span></td><td>{item.updated}</td><td><Link className="admin-edit-link" href={`/beheer/nieuws/${item.id}`} aria-label={`Bewerk ${item.title}`}><Pencil size={15} /><span>Bewerken</span></Link></td></tr>)}</tbody></table></div>{!visible.length && <div className="admin-empty"><Newspaper size={26} strokeWidth={1.4} /><h2>{items.length ? "Geen berichten gevonden" : "Nog geen nieuwsberichten"}</h2><p>{items.length ? "Probeer een andere zoekterm of status." : "Voeg een bericht toe en sla het op als concept of publiceer het op de website."}</p>{!items.length && <Link href="/beheer/nieuws/nieuw" className="button button-secondary">Eerste bericht maken</Link>}</div>}<div className="admin-list-count">{visible.length} van {items.length} berichten</div></div>;
}
