"use client";
/* eslint-disable @next/next/no-html-link-for-pages */
import { useActionState, useState } from "react";
import { useEditor, EditorContent } from "@tiptap/react";
import StarterKit from "@tiptap/starter-kit";
import LinkExtension from "@tiptap/extension-link";
import { savePostAction } from "@/lib/admin-actions";

type PostInput={id?:string;slug?:string;title?:string;excerpt?:string;content?:string;imageUrl?:string|null;imageAlt?:string|null;status?:string};
export function PostEditor({post={}}:{post?:PostInput}){const [state,action,pending]=useActionState(savePostAction,{});const [content,setContent]=useState(post.content||"<p>Schrijf hier uw nieuwsbericht…</p>");const editor=useEditor({immediatelyRender:false,extensions:[StarterKit.configure({heading:{levels:[2,3]}}),LinkExtension.configure({openOnClick:false,HTMLAttributes:{target:"_blank",rel:"noopener noreferrer"}})],content,onUpdate:({editor})=>setContent(editor.getHTML())});
  const setLink=()=>{const url=window.prompt("Naar welk webadres moet de link verwijzen?");if(url)editor?.chain().focus().extendMarkRange("link").setLink({href:url}).run()};
  return <form action={action} className="editor-card" encType="multipart/form-data"><input type="hidden" name="id" value={post.id||""}/><input type="hidden" name="slug" value={post.slug||""}/><input type="hidden" name="content" value={content}/><input type="hidden" name="existingImage" value={post.imageUrl||""}/>{state.error&&<div className="form-error" role="alert">{state.error}</div>}<div className="editor-grid"><div><div className="form-group"><label htmlFor="title">Titel</label><input className="input" id="title" name="title" defaultValue={post.title} maxLength={140} required/></div><div className="form-group"><label htmlFor="excerpt">Korte samenvatting</label><textarea className="input" id="excerpt" name="excerpt" defaultValue={post.excerpt} maxLength={320} required/></div><div className="form-group"><label>Inhoud</label><div className="editor-toolbar" aria-label="Tekstopmaak"><button type="button" onClick={()=>editor?.chain().focus().toggleBold().run()} className={editor?.isActive("bold")?"is-active":""}><strong>Vet</strong></button><button type="button" onClick={()=>editor?.chain().focus().toggleItalic().run()} className={editor?.isActive("italic")?"is-active":""}><em>Cursief</em></button><button type="button" onClick={()=>editor?.chain().focus().toggleHeading({level:2}).run()}>Kop</button><button type="button" onClick={()=>editor?.chain().focus().toggleBulletList().run()}>Lijst</button><button type="button" onClick={setLink}>Link</button></div><EditorContent editor={editor} className="editor-content"/></div></div><aside className="editor-side"><div className="form-group"><label htmlFor="status">Status</label><select className="input" id="status" name="status" defaultValue={post.status||"draft"}><option value="draft">Concept</option><option value="published">Gepubliceerd</option></select></div><div className="form-group"><label htmlFor="image">Hoofdafbeelding</label><input className="input" id="image" name="image" type="file" accept="image/jpeg,image/png,image/webp"/><p className="form-help">JPG, PNG of WebP, maximaal 5 MB.</p></div><div className="form-group"><label htmlFor="imageAlt">Beschrijving afbeelding</label><input className="input" id="imageAlt" name="imageAlt" defaultValue={post.imageAlt||""}/><p className="form-help">Beschrijf kort wat op de foto te zien is.</p></div></aside></div><div className="editor-actions"><button className="button button-primary" disabled={pending}>{pending?"Opslaan…":"Bericht opslaan"}</button><a className="button button-secondary" href="/beheer/nieuws">Annuleren</a></div></form>}
